In [2]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

In [3]:
load_dotenv()

DATABASE_URL = os.getenv("POSTGRES")

In [4]:

engine = create_engine(DATABASE_URL)

In [5]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public'
"""

tables = pd.read_sql(query, engine)

tables

   table_name
0  properties

In [8]:
df = pd.read_sql("SELECT * FROM properties", engine)

df.head()

,id,checksum,price,location,title,beds,baths,area,property_type,furnishing,amenities,link,reactivated_date,source,scraped_at,transformed_at
0,1852,9d7a952ad16fbdf505ef4d32318945a6,13000000,"Palm Hills New Cairo Compound, 5th Settlement",None,3,3.0,173.0,Apartment,Unfurnished,"Balcony, Private Garden, Security, Pool",https://www.dubizzle.com.eg/en/ad/lowest-downp...,2026-05-11 18:32:47.811,dubizzle,2026-05-11 18:32:47.811,2026-05-11 18:33:12.590428
1,2,e1a8744d5c417095655c2fadc395a4e0,12500000,"Shubra, Cairo",None,None,NaN,200.0,Office Space,Unfurnished,"Air Conditioning, Covered Parking",https://www.dubizzle.com.eg/en/ad/for-sale-a-h...,2026-05-09 11:07:41.679,dubizzle,2026-05-09 11:07:41.680,2026-05-10 18:27:16.054129
2,1853,241fcc3c6c78c0ebd9bd2f7185831adb,3400000,"Al Andalous, 5th Settlement",None,4,3.0,202.0,Apartment,None,"Private Garden, Pool, Electricity Meter, Water...",https://www.dubizzle.com.eg/en/ad/apartment-fo...,2026-05-11 18:32:48.585,dubizzle,2026-05-11 18:32:48.585,2026-05-11 18:33:13.002106
3,4,02ac686ec68f0d48ff0f7ad6a7410057,250000,"One Katameya, Katameya",None,None,NaN,260.0,Office Space,Furnished,Air Conditioning,https://www.dubizzle.com.eg/en/ad/for-rent-an-...,2026-05-09 11:08:18.180,dubizzle,2026-05-09 11:08:18.180,2026-05-10 18:27:16.827983
4,5,9cbddb0a16e1d839fc4451eca2617920,12500000,"Shubra, Cairo",None,None,NaN,200.0,Office Space,Unfurnished,"Air Conditioning, Covered Parking",https://www.dubizzle.com.eg/en/ad/for-sale-hea...,2026-05-09 13:55:43.702,dubizzle,2026-05-09 13:55:43.702,2026-05-10 18:27:17.172836

In [9]:
df.shape

(1976, 16)

In [10]:
df.columns

Index(['id', 'checksum', 'price', 'location', 'title', 'beds', 'baths', 'area',
       'property_type', 'furnishing', 'amenities', 'link', 'reactivated_date',
       'source', 'scraped_at', 'transformed_at'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1976 entries, 0 to 1975
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1976 non-null   int64
 1   checksum          1976 non-null   object
 2   price             1976 non-null   int64
 3   location          1976 non-null   object
 4   title             1767 non-null   object
 5   beds              1961 non-null   object
 6   baths             1961 non-null   float64
 7   area              1976 non-null   float64
 8   property_type     1976 non-null   object
 9   furnishing        1606 non-null   object
 10  amenities         1542 non-null   object
 11  link              1976 non-null   object
 12  reactivated_date  1976 non-null   datetime64[ns]
 13  source            1976 non-null   object
 14  scraped_at        1976 non-null   datetime64[ns]
 15  transformed_at    1976 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(2), object(9)
memory usage: 247.1+ KB

In [12]:
df.isnull().sum()

id                    0
checksum              0
price                 0
location              0
title               209
beds                 15
baths                15
area                  0
property_type         0
furnishing          370
amenities           434
link                  0
reactivated_date      0
source                0
scraped_at            0
transformed_at        0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.sample(10)

,id,checksum,price,location,title,beds,baths,area,property_type,furnishing,amenities,link,reactivated_date,source,scraped_at,transformed_at
1365,1602,3024ffd9916d9db6cc05903e2eab3a6d,234000000,"Katameya Dunes Compound, 5th Settlement, New C...",2 villas + penthouse for sale Direct view of g...,10,10.0,1880.0,Villa,None,"Electricity Meter, Water Meter, Natural Gas",https://www.bayut.eg/en/property/details-50338...,2026-04-17,bayut,2026-05-11 12:34:16.061,2026-05-11 12:44:32.018665
846,882,46cde23a598ef02fbafd1fdb21b36691,14514000,"City Gate Compound, 5th Settlement, New Cairo,...",Apartment for sale Fully Finished and Ready to...,2,3.0,145.0,Apartment,None,"Covered parking, Pets Allowed, Electricity Met...",https://www.bayut.eg/en/property/details-50344...,2026-04-29,bayut,2026-05-11 12:26:32.121,2026-05-11 12:39:55.833620
808,843,4f23ad84a104a56f4488de4533accf56,14499999,"EL Patio 7, 5th Settlement, New Cairo, Cairo","150m Super Lux Finishing With Prime View, Semi...",3,2.0,150.0,Penthouse,Furnished,"Built in Kitchen Appliances, Covered parking, ...",https://www.bayut.eg/en/property/details-50309...,2026-05-07,bayut,2026-05-11 12:23:56.090,2026-05-11 12:39:41.906581
115,117,477b43a015c01fc6f043a7a43318c56b,4000000,"Madinaty, Cairo",Apartment for sale with an area of 89 meters i...,2,2.0,89.0,Apartment,Unfurnished,"Pets Allowed, Electricity Meter, Water Meter, ...",https://www.bayut.eg/en/property/details-50347...,2026-05-06,bayut,2026-05-11 12:21:01.244,2026-05-11 12:35:25.777166
637,668,fc8530cf61c1f02205e1e9415e248cb9,3690000,"Ayyam, R8, New Capital City, Cairo","With 92,000Dp Apartment 3Bed at Special price ...",3,3.0,155.0,Apartment,Unfurnished,"Built in Kitchen Appliances, Covered parking, ...",https://www.bayut.eg/en/property/details-50348...,2026-05-07,bayut,2026-05-11 12:23:13.056,2026-05-11 12:38:39.757160
1476,1729,a6c7567b9e8d036bb555cffda2e033c6,14999999,"Fifth Square Compound, 5th Settlement, New Cai...",Kitchen & ACs | 165m Apartment For Sale In Fif...,3,3.0,165.0,Apartment,None,"Built in Kitchen Appliances, Covered parking, ...",https://www.bayut.eg/en/property/details-50338...,2026-04-19,bayut,2026-05-11 12:34:47.055,2026-05-11 12:45:19.649316
533,553,22360b5cdbb20b13fee77eadc8161c46,3600000,"Aljar, Sheraton, Cairo","Radytomove ull finishing, including air condit...",3,2.0,146.0,Apartment,None,"First Aid Medical Center, Gym or Health Club, ...",https://www.bayut.eg/en/property/details-50348...,2026-05-08,bayut,2026-05-11 12:22:45.596,2026-05-11 12:37:58.649314
1818,1142,2b5b0b84a3f950a002ee3f5bb2c53132,20000000,"Blue Vert, R7, New Capital City, Cairo",Pay in installments over 10 years and own a 22...,4,3.0,224.0,Townhouse,None,None,https://www.bayut.eg/en/property/details-50345...,2026-05-03,bayut,2026-05-11 12:29:21.116,2026-05-11 12:41:45.335329
1628,261,356f2c8393c2dc9928f4fa8388c42394,16275000,"Sodic East, New Heliopolis, Cairo",Villa For Sale In Sodic East New Cairo Ready T...,4,4.0,245.0,Villa,Furnished,None,https://www.bayut.eg/en/property/details-50346...,2026-05-04,bayut,2026-05-11 12:21:35.710,2026-05-11 12:36:16.485038
233,241,2a6b4011fce7e4fdf1326b6a175b0577,15500000,"Sodic East, New Heliopolis, Cairo",Ready to move Twin House for sale in Sodic Eas...,3,4.0,245.0,Twin House,None,"Covered parking, Pets Allowed, Electricity Met...",https://www.bayut.eg/en/property/details-50335...,2026-04-12,bayut,2026-05-11 12:21:30.954,2026-05-11 12:36:09.456307

In [15]:
df.to_csv("real_estate_data.csv", index=False)

In [19]:
df["beds"].value_counts(dropna=False)

beds
3         1013
2          364
4          322
5          112
1           59
6           45
Studio      21
None        15
7           11
8            5
9            3
10           3
11           3
Name: count, dtype: int64

In [20]:
df["beds"].dtype

dtype('O')

In [17]:
df[["price", "area", "property_type", "source"]].sort_values("price").head(20)

        price   area      property_type    source
6       25000  175.0       Office Space  dubizzle
1584    30000  210.0       Office Space  dubizzle
1582    35000  175.0       Office Space  dubizzle
1581    45000  200.0       Office Space  dubizzle
7       55000  270.0       Office Space  dubizzle
1583    60000  200.0       Office Space  dubizzle
1580    60000  200.0       Office Space  dubizzle
3      250000  260.0       Office Space  dubizzle
1960   800000  209.0               Land     bayut
701    800000   15.0          Apartment  dubizzle
1865   900000   40.0  Other Residential     bayut
1541  1000000   80.0          Apartment     bayut
1032  1100000   67.0          Apartment     bayut
838   1200000  130.0          Apartment  dubizzle
1056  1300000  140.0          Apartment     bayut
831   1400000  140.0          Apartment     bayut
508   1400000  115.0          Apartment     bayut
1496  1400000   70.0          Apartment     bayut
1528  1450000  120.0          Apartment     bayut
1867  1500000  420.0             Duplex     bayut

In [21]:
df["furnishing"].value_counts(dropna=False)

furnishing
Unfurnished    1484
None            370
Furnished       122
Name: count, dtype: int64

In [22]:
df["amenities"].isnull().sum()

np.int64(434)

In [23]:
df[df["amenities"].isnull()][
    ["source", "property_type", "location"]
].head(20)

       source    property_type                                       location
8    dubizzle        Apartment                            Wesal, Shorouk City
9    dubizzle           Studio                             Reve du nil, Maadi
18   dubizzle        Apartment  Galleria Moon Valley Compound, 5th Settlement
30   dubizzle  Hotel Apartment                                   Maadi, Cairo
57   dubizzle        Apartment                     New Fustat, Masr al-Kadema
112  dubizzle        Apartment                        Maadi Gardens, Katameya
125  dubizzle           Studio                                   Maadi, Cairo
165  dubizzle        Apartment                                Madinaty, Cairo
191  dubizzle        Apartment              Taj City Compound, 1st Settlement
204  dubizzle        Apartment              New Garden City, New Capital City
236  dubizzle        Apartment              Mountain View 1.1, 5th Settlement
246  dubizzle        Apartment                          Sarai, Mostakbal City
253  dubizzle        Apartment              Taj City Compound, 1st Settlement
258  dubizzle        Apartment                                Madinaty, Cairo
288  dubizzle        Apartment                          Sarai, Mostakbal City
392  dubizzle        Apartment                               Nasr City, Cairo
397  dubizzle        Apartment                            Shorouk City, Cairo
409  dubizzle        Apartment                            Shorouk City, Cairo
411  dubizzle        Apartment      Yellow residence Compound, 1st Settlement
461  dubizzle        Apartment                     Scenario, New Capital City

In [24]:
df["checksum"].duplicated().sum()

np.int64(0)

In [25]:
df.groupby(
    ["price", "location", "area", "beds"]
).size().sort_values(ascending=False).head(20)

price     location                                                        area   beds
17750000  Hyde Park New Cairo Compound, 5th Settlement, New Cairo, Cairo  160.0  3       5
7600000   Al Maqsad, New Capital City, Cairo                              135.0  3       4
7000000   Jade Park, R3, New Capital City, Cairo                          151.0  2       4
3500000   Obour City, Cairo                                               141.0  3       4
4562250   Defaf, R8, New Capital City, Cairo                              110.0  3       4
13850000  Hyde Park New Cairo Compound, 5th Settlement, New Cairo, Cairo  116.0  2       4
4700000   Madinaty, Cairo                                                 78.0   2       3
4800000   Madinaty, Cairo                                                 96.0   2       3
5625000   North Rehab, 1st Settlement, New Cairo, Cairo                   155.0  3       3
7100000   Sarai, Mostakbal City, Cairo                                    150.0  3       3
5500000   Madinaty, Cairo                                                 96.0   2       3
10000000  Blue Vert, R7, New Capital City, Cairo                          146.0  3       3
6300000   Bloomfields, Mostakbal City, Cairo                              135.0  2       2
5400000   Madinaty, Cairo                                                 96.0   2       2
7300000   Madinaty, Cairo                                                 109.0  3       2
7000000   Madinaty, Cairo                                                 131.0  3       2
6000000   Taj City Compound, 1st Settlement, New Cairo, Cairo             166.0  3       2
9000000   Madinaty, Cairo                                                 178.0  3       2
5800000   The Icon Residence Compound, 5th Settlement, New Cairo, Cairo   125.0  2       2
4400000   Al Maqsad, New Capital City, Cairo                              161.0  3       2
dtype: int64

In [26]:
df["location"].sample(20)

1119    Safwa Al Andalus, 5th Settlement, New Cairo, C...
228     Mivida Compound, 5th Settlement, New Cairo, Cairo
913     90 Avenue Compound, 5th Settlement, New Cairo,...
771                                 Sarai, Mostakbal City
174     City Gate Compound, 5th Settlement, New Cairo,...
1028                   Noor City, New Capital City, Cairo
1580                      Rayhanah Plaza, Zahraa Al Maadi
877                                       Madinaty, Cairo
1578     Jiwar Compound, 6th Settlement, New Cairo, Cairo
362                                       Madinaty, Cairo
1279                                      Madinaty, Cairo
1410    Hyde Park New Cairo Compound, 5th Settlement, ...
1251                         Sarai, Mostakbal City, Cairo
1405     layan Compound, 5th Settlement, New Cairo, Cairo
1208    City Gate Compound, 5th Settlement, New Cairo,...
1849    Palm Hills New Cairo Compound, 5th Settlement,...
715                De Joya 4, R8, New Capital City, Cairo
484     Rock Vera Compound, 5th Settlement, New Cairo,...
1335              Jadie, 5th Settlement, New Cairo, Cairo
235     Mivida Compound, 5th Settlement, New Cairo, Cairo
Name: location, dtype: object

In [27]:
dupes = df.groupby(
    ["price", "location", "area", "beds"]
).size().reset_index(name="count")

dupes = dupes[dupes["count"] > 1]

dupes.sort_values("count", ascending=False).head(20)

,price,location,area,beds,count
1468,17750000,"Hyde Park New Cairo Compound, 5th Settlement, ...",160.0,3,5
301,4562250,"Defaf, R8, New Capital City, Cairo",110.0,3,4
140,3500000,"Obour City, Cairo",141.0,3,4
779,7600000,"Al Maqsad, New Capital City, Cairo",135.0,3,4
1293,13850000,"Hyde Park New Cairo Compound, 5th Settlement, ...",116.0,2,4
690,7000000,"Jade Park, R3, New Capital City, Cairo",151.0,2,4
336,4800000,"Madinaty, Cairo",96.0,2,3
709,7100000,"Sarai, Mostakbal City, Cairo",150.0,3,3
469,5625000,"North Rehab, 1st Settlement, New Cairo, Cairo",155.0,3,3
436,5500000,"Madinaty, Cairo",96.0,2,3
317,4700000,"Madinaty, Cairo",78.0,2,3
1026,10000000,"Blue Vert, R7, New Capital City, Cairo",146.0,3,3
292,4500000,"Sarai, Mostakbal City, Cairo",124.0,2,2
242,4250000,"Shorouk City, Cairo",195.0,3,2
178,3785513,"Defaf, R8, New Capital City, Cairo",95.0,2,2
456,5500000,"The Icon Residence Compound, 5th Settlement, N...",162.0,3,2
495,5800000,"The Icon Residence Compound, 5th Settlement, N...",125.0,2,2
505,5900000,"Hyde Park New Cairo Compound, 5th Settlement, ...",71.0,1,2
421,5400000,"Madinaty, Cairo",96.0,2,2
547,6000000,"Sarai, Mostakbal City, Cairo",131.0,3,2

In [28]:
sample_dup = dupes.iloc[0]

df[
    (df["price"] == sample_dup["price"]) &
    (df["location"] == sample_dup["location"]) &
    (df["area"] == sample_dup["area"]) &
    (df["beds"] == sample_dup["beds"])
][
    [
        "title",
        "price",
        "location",
        "area",
        "beds",
        "amenities",
        "scraped_at",
        "link"
    ]
]

,title,price,location,area,beds,amenities,scraped_at,link
1821,Pay in installments over 12 years and own a 3-...,3075975,"Defaf, R8, New Capital City, Cairo",155.0,3,None,2026-05-11 12:29:21.786,https://www.bayut.eg/en/property/details-50345...
1825,Pay in installments over 12 years and own a 3-...,3075975,"Defaf, R8, New Capital City, Cairo",155.0,3,None,2026-05-11 12:29:22.688,https://www.bayut.eg/en/property/details-50345...

In [29]:
fuzzy_dupes = df.groupby(
    ["location", "area", "beds"]
).size().reset_index(name="count")

fuzzy_dupes = fuzzy_dupes[fuzzy_dupes["count"] > 1]

fuzzy_dupes.sort_values("count", ascending=False).head(20)

                                               location   area beds  count
720                                     Madinaty, Cairo   96.0    2     12
377   EL Patio ORO Compound, 5th Settlement, New Cai...  164.0    3     11
711                                     Madinaty, Cairo   78.0    2      7
560   Hyde Park New Cairo Compound, 5th Settlement, ...  160.0    3      7
730                                     Madinaty, Cairo  116.0    3      7
1256                       Sarai, Mostakbal City, Cairo  212.0    4      7
553   Hyde Park New Cairo Compound, 5th Settlement, ...  116.0    2      6
924   Mountain View iCity Compound, 5th Settlement, ...  235.0    3      6
759                                     Madinaty, Cairo  211.0    3      6
739                                     Madinaty, Cairo  140.0    3      6
918   Mountain View iCity Compound, 5th Settlement, ...  165.0    3      6
1138                       Rehab City, New Cairo, Cairo   90.0    2      6
1415  Taj City Compound, 1st Settlement, New Cairo, ...  166.0    3      6
751                                     Madinaty, Cairo  175.0    3      5
109                  Al Maqsad, New Capital City, Cairo  135.0    3      5
379   EL Patio ORO Compound, 5th Settlement, New Cai...  171.0    3      5
108                  Al Maqsad, New Capital City, Cairo  134.0    3      5
726                                     Madinaty, Cairo  107.0    2      5
752                                     Madinaty, Cairo  178.0    3      5
1364          Stone Residence Compound, Katameya, Cairo  220.0    3      5

In [30]:
sample = fuzzy_dupes.iloc[0]

df[
    (df["location"] == sample["location"]) &
    (df["area"] == sample["area"]) &
    (df["beds"] == sample["beds"])
][
    [
        "title",
        "price",
        "location",
        "area",
        "beds",
        "scraped_at",
        "link"
    ]
]

,title,price,location,area,beds,scraped_at,link
154,Apartment For Sale 115m Corner North Facing Di...,3225000,"3rd Settlement, New Cairo, Cairo",115.0,3,2026-05-11 12:21:11.143,https://www.bayut.eg/en/property/details-50313...
917,"Apartment for sale in Sakan Misr, Exhibition G...",2800000,"3rd Settlement, New Cairo, Cairo",115.0,3,2026-05-11 12:26:58.480,https://www.bayut.eg/en/property/details-50346...

In [31]:
sample = fuzzy_dupes.iloc[0]

test = df[
    (df["location"] == sample["location"]) &
    (df["area"] == sample["area"]) &
    (df["beds"] == sample["beds"])
]

test[["price", "title", "link", "scraped_at"]]

,price,title,link,scraped_at
154,3225000,Apartment For Sale 115m Corner North Facing Di...,https://www.bayut.eg/en/property/details-50313...,2026-05-11 12:21:11.143
917,2800000,"Apartment for sale in Sakan Misr, Exhibition G...",https://www.bayut.eg/en/property/details-50346...,2026-05-11 12:26:58.480

In [32]:
df["listing_id"] = df["link"].str.extract(r'(\d+)')

In [33]:
df["listing_id"].duplicated().sum()

np.int64(78)

In [34]:
dupe_ids = df[df["listing_id"].duplicated(keep=False)]

dupe_ids.sort_values("listing_id")[
    [
        "listing_id",
        "price",
        "title",
        "scraped_at",
        "link"
    ]
].head(20)

,listing_id,price,title,scraped_at,link
523,1,17000000,None,2026-05-11 18:33:07.081,https://www.dubizzle.com.eg/en/ad/moon-valley-...
878,1,5150000,None,2026-05-11 18:57:33.614,https://www.dubizzle.com.eg/en/ad/garden-view-...
662,1,11750000,None,2026-05-11 18:57:26.240,https://www.dubizzle.com.eg/en/ad/luxury-apart...
526,10,13338727,None,2026-05-11 18:33:07.875,https://www.dubizzle.com.eg/en/ad/apartment-fo...
458,10,18500000,None,2026-05-11 18:33:05.005,https://www.dubizzle.com.eg/en/ad/lowest-down-...
15,10,8500000,None,2026-05-10 18:26:55.731,https://www.dubizzle.com.eg/en/ad/best-price-i...
857,10,11000000,None,2026-05-11 18:57:32.640,https://www.dubizzle.com.eg/en/ad/my-city-b10-...
48,11,4100000,None,2026-05-10 18:27:03.224,https://www.dubizzle.com.eg/en/ad/for-sale-in-...
1593,11,6200000,None,2026-05-10 18:27:05.500,https://www.dubizzle.com.eg/en/ad/apartment-fo...
265,136,3981955,None,2026-05-11 18:32:58.832,https://www.dubizzle.com.eg/en/ad/apartment-fo...
165,136,9100000,None,2026-05-11 18:32:54.768,https://www.dubizzle.com.eg/en/ad/apartment-13...
782,136,9100000,None,2026-05-11 18:57:30.026,https://www.dubizzle.com.eg/en/ad/136-sqm-grou...
112,145,3400000,None,2026-05-11 18:32:53.134,https://www.dubizzle.com.eg/en/ad/apartment-fo...
397,145,2900000,None,2026-05-11 18:33:02.737,https://www.dubizzle.com.eg/en/ad/145-sqm-rear...
1590,168,13420000,None,2026-05-10 18:27:01.629,https://www.dubizzle.com.eg/en/ad/lowest-down-...
1596,168,10086000,None,2026-05-10 18:27:06.386,https://www.dubizzle.com.eg/en/ad/apartment-16...
1598,168,10086000,None,2026-05-10 18:27:07.304,https://www.dubizzle.com.eg/en/ad/apartment-16...
155,168,10800000,None,2026-05-11 18:32:54.535,https://www.dubizzle.com.eg/en/ad/apartment-in...
12,171,3167000,None,2026-05-10 18:26:54.772,https://www.dubizzle.com.eg/en/ad/apartment-17...
1595,171,11760000,None,2026-05-10 18:27:06.163,https://www.dubizzle.com.eg/en/ad/apartment-17...

In [35]:
sample_id = dupe_ids["listing_id"].iloc[0]

df[df["listing_id"] == sample_id][
    [
        "price",
        "title",
        "amenities",
        "scraped_at",
        "link"
    ]
]

,price,title,amenities,scraped_at,link
1,12500000,None,"Air Conditioning, Covered Parking",2026-05-09 11:07:41.680,https://www.dubizzle.com.eg/en/ad/for-sale-a-h...
4,12500000,None,"Air Conditioning, Covered Parking",2026-05-09 13:55:43.702,https://www.dubizzle.com.eg/en/ad/for-sale-hea...

In [36]:
df = df.sort_values("scraped_at")

In [37]:
df_latest = df.drop_duplicates(
    subset="listing_id",
    keep="last"
)

In [38]:
print(len(df))
print(len(df_latest))

1976
1898

In [39]:
df_analysis = df_latest.copy()

In [40]:
df_analysis["is_studio"] = (
    df_analysis["beds"] == "Studio"
)

df_analysis["beds_clean"] = pd.to_numeric(
    df_analysis["beds"],
    errors="coerce"
).astype("Int64")

In [41]:
df_analysis[
    ["beds", "beds_clean", "is_studio"]
].sample(15)

        beds  beds_clean  is_studio
1581    None        <NA>      False
808        3           3      False
577        3           3      False
1433  Studio        <NA>       True
591        3           3      False
1185       5           5      False
1795       3           3      False
1777       2           2      False
1280       2           2      False
61         3           3      False
552        1           1      False
137        3           3      False
1893       4           4      False
467        5           5      False
1374       3           3      False

In [42]:
df_analysis["beds_clean"].dtype

Int64Dtype()

In [43]:
df_analysis["price"].head()

1581       45000
3         250000
4       12500000
6          25000
7          55000
Name: price, dtype: int64

In [44]:
df_analysis["price"].dtype

dtype('int64')

In [45]:
df_analysis["price_clean"] = pd.to_numeric(
    df_analysis["price"],
    errors="coerce"
)

In [46]:
df_analysis["price_clean"].describe()

count    1.898000e+03
mean     1.439512e+07
std      1.868315e+07
min      2.500000e+04
25%      5.591120e+06
50%      9.000000e+06
75%      1.625509e+07
max      3.120000e+08
Name: price_clean, dtype: float64

In [47]:
df_analysis["price_per_sqm"] = (
    df_analysis["price_clean"] /
    df_analysis["area"]
)

In [48]:
df_analysis["price_per_sqm"].describe()

count      1898.000000
mean      60728.852161
std       35753.377348
min         142.857143
25%       36290.322581
50%       54000.000000
75%       75519.606135
max      423529.411765
Name: price_per_sqm, dtype: float64

In [49]:
df_analysis.sort_values(
    "price_per_sqm"
)[
    [
        "price_clean",
        "area",
        "price_per_sqm",
        "property_type",
        "location",
        "link"
    ]
].head(20)

,price_clean,area,price_per_sqm,property_type,location,link
6,25000,175.0,142.857143,Office Space,"Laurent, Alexandria",https://www.dubizzle.com.eg/en/ad/office-for-r...
1584,30000,210.0,142.857143,Office Space,"Darna, Zahraa Al Maadi",https://www.dubizzle.com.eg/en/ad/office-headq...
7,55000,270.0,203.703704,Office Space,"Smoha, Alexandria",https://www.dubizzle.com.eg/en/ad/distinct-adm...
1581,45000,200.0,225.000000,Office Space,"Bavaria Town, Zahraa Al Maadi",https://www.dubizzle.com.eg/en/ad/administrati...
1583,60000,200.0,300.000000,Office Space,"Rayhanah Plaza, Zahraa Al Maadi",https://www.dubizzle.com.eg/en/ad/for-rent-an-...
3,250000,260.0,961.538462,Office Space,"One Katameya, Katameya",https://www.dubizzle.com.eg/en/ad/for-rent-an-...
1867,1500000,420.0,3571.428571,Duplex,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50345...
1960,800000,209.0,3827.751196,Land,"New Obour City, Obour City, Cairo",https://www.bayut.eg/en/property/details-50344...
1905,1800000,300.0,6000.000000,Duplex,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50330...
1068,1700000,280.0,6071.428571,Duplex,"El Motamayez District, Badr City, Cairo",https://www.bayut.eg/en/property/details-50344...
1064,3000000,400.0,7500.000000,Duplex,"El Motamayez District, Badr City, Cairo",https://www.bayut.eg/en/property/details-50344...
1056,1300000,140.0,9285.714286,Apartment,"El Motamayez District, Badr City, Cairo",https://www.bayut.eg/en/property/details-50344...
831,1400000,140.0,10000.000000,Apartment,"El Motamayez District, Badr City, Cairo",https://www.bayut.eg/en/property/details-50348...
1529,1500000,145.0,10344.827586,Apartment,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50096...
113,8000000,700.0,11428.571429,Villa,"Mivida Compound, 5th Settlement, New Cairo, Cairo",https://www.bayut.eg/en/property/details-20501...
1711,5200000,450.0,11555.555556,Duplex,"Shorouk City, Cairo",https://www.bayut.eg/en/property/details-50348...
1528,1450000,120.0,12083.333333,Apartment,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50327...
508,1400000,115.0,12173.913043,Apartment,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50301...
1541,1000000,80.0,12500.000000,Apartment,"Hadayeq El Zeitoun, Cairo",https://www.bayut.eg/en/property/details-50299...
1650,4200000,330.0,12727.272727,Duplex,"Shorouk City, Cairo",https://www.bayut.eg/en/property/details-50349...

In [51]:
import numpy as np


df_analysis["transaction_type"] = np.where(
    df_analysis["link"].str.contains("for-rent"),
    "for_rent",
    "for_sale"
)

In [52]:
df_analysis["transaction_type"].value_counts()

transaction_type
for_sale    1892
for_rent       6
Name: count, dtype: int64

In [53]:
df_analysis.groupby(
    "transaction_type"
)["price_per_sqm"].describe()

,count,mean,std,min,25%,50%,75%,max
transaction_type,,,,,,,,
for_rent,6.0,329.326075,315.201128,142.857143,158.068783,214.351852,281.250000,961.538462
for_sale,1892.0,60920.393998,35647.550114,3571.428571,36443.850267,54064.064064,75557.109888,423529.411765

In [54]:
df_analysis["amenities"].dropna().sample(10)

1395    Covered parking, Electricity Backup, Pets Allo...
1082    Covered parking, Maintenance Staff, Cleaning S...
844     Covered parking, Pets Allowed, Water Meter, Na...
291     Balcony, Private Garden, Central A/C & heating...
101                              Private Garden, Security
277     Covered parking, Pets Allowed, Electricity Met...
1170    Covered parking, Electricity Meter, Water Mete...
1425    Covered parking, Pets Allowed, Electricity Met...
1125    Covered parking, Electricity Meter, Water Mete...
1203    Balcony or Terrace, Covered parking, Lawn or G...
Name: amenities, dtype: object

In [55]:
all_amenities = (
    df_analysis["amenities"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

all_amenities.value_counts().head(50)

amenities
Electricity Meter              1003
Security Staff                  908
Water Meter                     906
Natural Gas                     899
Lawn or Garden                  889
Covered parking                 877
Pets Allowed                    837
Balcony or Terrace              806
Landline                        777
Gym or Health Club              754
Kids Play Area                  752
Barbeque Area                   687
CCTV Security                   645
Maintenance Staff               635
Swimming Pool                   625
Cafeteria or Canteen            582
Day Care Center                 555
First Aid Medical Center        546
Cleaning Services               537
Jacuzzi                         492
Built in Kitchen Appliances     478
Waste Disposal                  476
Sauna                           432
Facilities for Disabled         415
24 Hours Concierge              414
Broadband Internet              392
Steam Room                      380
Satellite/Cable TV              349
Lobby in Building               342
Business Center                 341
Intercom                        336
Laundry Room                    332
Freehold                        290
Laundry Facility                283
Conference Room                 278
Maids Room                      245
Shared Kitchen                  240
Double Glazed Windows           233
Service Elevators               226
Storage Areas                   219
Reception/Waiting Room          219
Central A/C & heating           215
Electricity Backup              211
Centrally Air-Conditioned       196
Prayer Room                     173
ATM Facility                    166
Central Heating                 163
Study Room                      137
Sea view                        132
Furnished                       118
Name: count, dtype: int64

In [56]:
amenity_map = {

    "Central A/C & heating": "Central AC",

    "Centrally Air-Conditioned": "Central AC",

    "Laundry Facility": "Laundry",

    "Laundry Room": "Laundry",

    "Balcony or Terrace": "Balcony",

    "Covered parking": "Covered Parking"

}

In [59]:
amenity_map = {

    "Central A/C & heating": "Central AC",

    "Centrally Air-Conditioned": "Central AC",

    "Laundry Facility": "Laundry",

    "Laundry Room": "Laundry",

    "Balcony or Terrace": "Balcony",

    "Covered parking": "Covered Parking"

}

def normalize_amenities(text):

    if pd.isna(text):
        return None

    items = [
        x.strip()
        for x in text.split(",")
    ]

    normalized = [
        amenity_map.get(item, item)
        for item in items
    ]

    return ", ".join(
        sorted(set(normalized))
    )

In [60]:
df_analysis["amenities_clean"] = (
    df_analysis["amenities"]
    .apply(normalize_amenities)
)

In [61]:
df_analysis[
    ["amenities", "amenities_clean"]
].sample(10)

,amenities,amenities_clean
127,"Covered parking, Pets Allowed, Parking Spaces:...","24 Hours Concierge, Balcony, Barbeque Area, Bu..."
378,"Pets Allowed, Water Meter, Natural Gas, Landli...","24 Hours Concierge, Balcony, Broadband Interne..."
1405,"Covered parking, Pets Allowed, Parking Spaces:...","Balcony, Covered Parking, Electricity Meter, F..."
500,"Built in Kitchen Appliances, Covered parking, ...","24 Hours Concierge, ATM Facility, Balcony, Bar..."
1867,None,None
1311,"Electricity Meter, Natural Gas, Gym or Health ...","CCTV Security, Cleaning Services, Electricity ..."
1600,None,None
104,"Covered parking, Electricity Backup, Electrici...","24 Hours Concierge, Balcony, Barbeque Area, CC..."
1262,"Balcony or Terrace, Covered parking, Reception...","Balcony, Cleaning Services, Covered Parking, M..."
1736,None,None