In [2]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

In [3]:
load_dotenv()

DATABASE_URL = os.getenv("POSTGRES")

In [4]:

engine = create_engine(DATABASE_URL)

In [5]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema='public'
"""

tables = pd.read_sql(query, engine)

tables

         table_name
0        properties
1  clean_properties

In [8]:
df = pd.read_sql("SELECT * FROM properties", engine)

df.head()

,id,checksum,price,location,title,beds,baths,area,property_type,furnishing,amenities,link,reactivated_date,source,scraped_at,transformed_at
0,1852,9d7a952ad16fbdf505ef4d32318945a6,13000000,"Palm Hills New Cairo Compound, 5th Settlement",NaN,3,3.0,173.0,Apartment,Unfurnished,"Balcony, Private Garden, Security, Pool",https://www.dubizzle.com.eg/en/ad/lowest-downp...,2026-05-11 18:32:47.811,dubizzle,2026-05-11 18:32:47.811,2026-05-11 18:33:12.590428
1,2,e1a8744d5c417095655c2fadc395a4e0,12500000,"Shubra, Cairo",NaN,NaN,NaN,200.0,Office Space,Unfurnished,"Air Conditioning, Covered Parking",https://www.dubizzle.com.eg/en/ad/for-sale-a-h...,2026-05-09 11:07:41.679,dubizzle,2026-05-09 11:07:41.680,2026-05-10 18:27:16.054129
2,1853,241fcc3c6c78c0ebd9bd2f7185831adb,3400000,"Al Andalous, 5th Settlement",NaN,4,3.0,202.0,Apartment,NaN,"Private Garden, Pool, Electricity Meter, Water...",https://www.dubizzle.com.eg/en/ad/apartment-fo...,2026-05-11 18:32:48.585,dubizzle,2026-05-11 18:32:48.585,2026-05-11 18:33:13.002106
3,4,02ac686ec68f0d48ff0f7ad6a7410057,250000,"One Katameya, Katameya",NaN,NaN,NaN,260.0,Office Space,Furnished,Air Conditioning,https://www.dubizzle.com.eg/en/ad/for-rent-an-...,2026-05-09 11:08:18.180,dubizzle,2026-05-09 11:08:18.180,2026-05-10 18:27:16.827983
4,5,9cbddb0a16e1d839fc4451eca2617920,12500000,"Shubra, Cairo",NaN,NaN,NaN,200.0,Office Space,Unfurnished,"Air Conditioning, Covered Parking",https://www.dubizzle.com.eg/en/ad/for-sale-hea...,2026-05-09 13:55:43.702,dubizzle,2026-05-09 13:55:43.702,2026-05-10 18:27:17.172836

In [9]:
df.shape

(2062, 16)

In [10]:
df.columns

Index(['id', 'checksum', 'price', 'location', 'title', 'beds', 'baths', 'area',
       'property_type', 'furnishing', 'amenities', 'link', 'reactivated_date',
       'source', 'scraped_at', 'transformed_at'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1976 entries, 0 to 1975
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1976 non-null   int64
 1   checksum          1976 non-null   object
 2   price             1976 non-null   int64
 3   location          1976 non-null   object
 4   title             1767 non-null   object
 5   beds              1961 non-null   object
 6   baths             1961 non-null   float64
 7   area              1976 non-null   float64
 8   property_type     1976 non-null   object
 9   furnishing        1606 non-null   object
 10  amenities         1542 non-null   object
 11  link              1976 non-null   object
 12  reactivated_date  1976 non-null   datetime64[ns]
 13  source            1976 non-null   object
 14  scraped_at        1976 non-null   datetime64[ns]
 15  transformed_at    1976 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(2), object(9)
memory usage: 247.1+ KB

In [12]:
df.isnull().sum()

id                    0
checksum              0
price                 0
location              0
title               209
beds                 15
baths                15
area                  0
property_type         0
furnishing          370
amenities           434
link                  0
reactivated_date      0
source                0
scraped_at            0
transformed_at        0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.sample(10)

,id,checksum,price,location,title,beds,baths,area,property_type,furnishing,amenities,link,reactivated_date,source,scraped_at,transformed_at
305,315,90f0f558c70bd7fe64c6b01004cd3f22,5250000,"New Narges, 5th Settlement, New Cairo, Cairo",175 sqm space (North facing) in Al-Narjis Al-J...,3,3.0,175.0,Apartment,Unfurnished,"Completion Year: 2, Freehold",https://www.bayut.eg/en/property/details-50296...,2025-12-21,bayut,2026-05-11 12:21:48.338,2026-05-11 12:36:35.354086
1090,1154,fc04f897ef0b0e059a0bdff728aff5a4,4800000,"Kardia, New Capital City, Cairo","Apartment 3Bed for sale ready for viewing, at ...",3,3.0,148.0,Apartment,Unfurnished,"Built in Kitchen Appliances, Covered parking, ...",https://www.bayut.eg/en/property/details-50345...,2026-05-03,bayut,2026-05-11 12:29:23.814,2026-05-11 12:41:49.565524
183,188,e58b5480f46930fb770873e4e02d5c93,24000000,"Madinaty, Cairo","For sale in Madinaty, a twin house villa, Z, p...",3,3.0,251.0,Villa,Unfurnished,"Built in Kitchen Appliances, Covered parking, ...",https://www.bayut.eg/en/property/details-50348...,2026-05-07,bayut,2026-05-11 12:21:18.440,2026-05-11 12:35:51.086818
1540,1706,2813677a69efca75a69ffdc738399c31,38890000,"Madinaty, Cairo","villa for sale in madinaty, design C3, open wi...",5,4.0,319.0,Villa,Unfurnished,"Covered parking, Pets Allowed, Parking Spaces:...",https://www.bayut.eg/en/property/details-50248...,2026-04-19,bayut,2026-05-11 12:34:41.829,2026-05-11 12:45:11.079698
1486,1642,a5479a58581af85ed09a5ad5a8f1e8bc,3256000,"Shorouk City, Cairo",176m² front-facing apartment in the Fifth Sett...,3,2.0,176.0,Apartment,Unfurnished,"Covered parking, Electricity Meter, Water Meter",https://www.bayut.eg/en/property/details-50304...,2026-05-02,bayut,2026-05-11 12:34:25.535,2026-05-11 12:44:47.175401
460,476,01aeafbd7dd35342e0eeceab565caffb,13473000,"Maadi View, Shorouk City, Cairo",Villa for sale with a landscape view at the lo...,4,4.0,360.0,Villa,Furnished,"Built in Kitchen Appliances, Furnished, Covere...",https://www.bayut.eg/en/property/details-50348...,2026-05-09,bayut,2026-05-11 12:22:27.338,2026-05-11 12:37:31.786204
1542,1708,a5088a2922df655f1478c0c35bb5b566,14400000,"Talala, New Heliopolis, Cairo",A unique opportunity to own a fully finished v...,5,5.0,246.0,Villa,Unfurnished,"Covered parking, Electricity Backup, Pets Allo...",https://www.bayut.eg/en/property/details-50338...,2026-04-19,bayut,2026-05-11 12:34:42.283,2026-05-11 12:45:11.765914
1814,808,2f3e3c46c6b4017c5534ad9eacdcc676,6000000,"Mountain View 1.1, 5th Settlement, New Cairo, ...",Limited time Down payment equals instant disco...,3,3.0,156.0,Apartment,Unfurnished,NaN,https://www.bayut.eg/en/property/details-50348...,2026-05-09,bayut,2026-05-11 12:23:47.744,2026-05-11 12:39:28.561122
1336,1431,253315e0b55240530bf77180b1ae3a45,3100000,"Taj City Compound, 1st Settlement, New Cairo, ...",Your apartment in Taj City boasts a prime loca...,3,2.0,130.0,Apartment,NaN,"Electricity Meter, Water Meter, Natural Gas, L...",https://www.bayut.eg/en/property/details-50341...,2026-05-04,bayut,2026-05-11 12:33:33.489,2026-05-11 12:43:30.615948
676,709,ab600336c99e3736bd0a617a04d02100,13400000,"Rehab City, New Cairo, Cairo",Opportunity apartment at the old price for inv...,3,2.0,150.0,Hotel Apartment,Furnished,"Built in Kitchen Appliances, Furnished, Covere...",https://www.bayut.eg/en/property/details-50348...,2026-05-09,bayut,2026-05-11 12:23:22.998,2026-05-11 12:38:54.074364

In [15]:
df.to_csv("real_estate_data.csv", index=False)

In [19]:
df["beds"].value_counts(dropna=False)

beds
3         1013
2          364
4          322
5          112
1           59
6           45
Studio      21
None        15
7           11
8            5
9            3
10           3
11           3
Name: count, dtype: int64

In [20]:
df["beds"].dtype

dtype('O')

In [17]:
df[["price", "area", "property_type", "source"]].sort_values("price").head(20)

        price   area      property_type    source
6       25000  175.0       Office Space  dubizzle
1584    30000  210.0       Office Space  dubizzle
1582    35000  175.0       Office Space  dubizzle
1581    45000  200.0       Office Space  dubizzle
7       55000  270.0       Office Space  dubizzle
1583    60000  200.0       Office Space  dubizzle
1580    60000  200.0       Office Space  dubizzle
3      250000  260.0       Office Space  dubizzle
1960   800000  209.0               Land     bayut
701    800000   15.0          Apartment  dubizzle
1865   900000   40.0  Other Residential     bayut
1541  1000000   80.0          Apartment     bayut
1032  1100000   67.0          Apartment     bayut
838   1200000  130.0          Apartment  dubizzle
1056  1300000  140.0          Apartment     bayut
831   1400000  140.0          Apartment     bayut
508   1400000  115.0          Apartment     bayut
1496  1400000   70.0          Apartment     bayut
1528  1450000  120.0          Apartment     bayut
1867  1500000  420.0             Duplex     bayut

In [21]:
df["furnishing"].value_counts(dropna=False)

furnishing
Unfurnished    1484
None            370
Furnished       122
Name: count, dtype: int64

In [22]:
df["amenities"].isnull().sum()

np.int64(434)

In [23]:
df[df["amenities"].isnull()][
    ["source", "property_type", "location"]
].head(20)

       source    property_type                                       location
8    dubizzle        Apartment                            Wesal, Shorouk City
9    dubizzle           Studio                             Reve du nil, Maadi
18   dubizzle        Apartment  Galleria Moon Valley Compound, 5th Settlement
30   dubizzle  Hotel Apartment                                   Maadi, Cairo
57   dubizzle        Apartment                     New Fustat, Masr al-Kadema
112  dubizzle        Apartment                        Maadi Gardens, Katameya
125  dubizzle           Studio                                   Maadi, Cairo
165  dubizzle        Apartment                                Madinaty, Cairo
191  dubizzle        Apartment              Taj City Compound, 1st Settlement
204  dubizzle        Apartment              New Garden City, New Capital City
236  dubizzle        Apartment              Mountain View 1.1, 5th Settlement
246  dubizzle        Apartment                          Sarai, Mostakbal City
253  dubizzle        Apartment              Taj City Compound, 1st Settlement
258  dubizzle        Apartment                                Madinaty, Cairo
288  dubizzle        Apartment                          Sarai, Mostakbal City
392  dubizzle        Apartment                               Nasr City, Cairo
397  dubizzle        Apartment                            Shorouk City, Cairo
409  dubizzle        Apartment                            Shorouk City, Cairo
411  dubizzle        Apartment      Yellow residence Compound, 1st Settlement
461  dubizzle        Apartment                     Scenario, New Capital City

In [24]:
df["checksum"].duplicated().sum()

np.int64(0)

In [25]:
df.groupby(
    ["price", "location", "area", "beds"]
).size().sort_values(ascending=False).head(20)

price     location                                                        area   beds
17750000  Hyde Park New Cairo Compound, 5th Settlement, New Cairo, Cairo  160.0  3       5
7600000   Al Maqsad, New Capital City, Cairo                              135.0  3       4
7000000   Jade Park, R3, New Capital City, Cairo                          151.0  2       4
3500000   Obour City, Cairo                                               141.0  3       4
4562250   Defaf, R8, New Capital City, Cairo                              110.0  3       4
13850000  Hyde Park New Cairo Compound, 5th Settlement, New Cairo, Cairo  116.0  2       4
4700000   Madinaty, Cairo                                                 78.0   2       3
4800000   Madinaty, Cairo                                                 96.0   2       3
5625000   North Rehab, 1st Settlement, New Cairo, Cairo                   155.0  3       3
7100000   Sarai, Mostakbal City, Cairo                                    150.0  3       3
5500000   Madinaty, Cairo                                                 96.0   2       3
10000000  Blue Vert, R7, New Capital City, Cairo                          146.0  3       3
6300000   Bloomfields, Mostakbal City, Cairo                              135.0  2       2
5400000   Madinaty, Cairo                                                 96.0   2       2
7300000   Madinaty, Cairo                                                 109.0  3       2
7000000   Madinaty, Cairo                                                 131.0  3       2
6000000   Taj City Compound, 1st Settlement, New Cairo, Cairo             166.0  3       2
9000000   Madinaty, Cairo                                                 178.0  3       2
5800000   The Icon Residence Compound, 5th Settlement, New Cairo, Cairo   125.0  2       2
4400000   Al Maqsad, New Capital City, Cairo                              161.0  3       2
dtype: int64

In [26]:
df["location"].sample(20)

1119    Safwa Al Andalus, 5th Settlement, New Cairo, C...
228     Mivida Compound, 5th Settlement, New Cairo, Cairo
913     90 Avenue Compound, 5th Settlement, New Cairo,...
771                                 Sarai, Mostakbal City
174     City Gate Compound, 5th Settlement, New Cairo,...
1028                   Noor City, New Capital City, Cairo
1580                      Rayhanah Plaza, Zahraa Al Maadi
877                                       Madinaty, Cairo
1578     Jiwar Compound, 6th Settlement, New Cairo, Cairo
362                                       Madinaty, Cairo
1279                                      Madinaty, Cairo
1410    Hyde Park New Cairo Compound, 5th Settlement, ...
1251                         Sarai, Mostakbal City, Cairo
1405     layan Compound, 5th Settlement, New Cairo, Cairo
1208    City Gate Compound, 5th Settlement, New Cairo,...
1849    Palm Hills New Cairo Compound, 5th Settlement,...
715                De Joya 4, R8, New Capital City, Cairo
484     Rock Vera Compound, 5th Settlement, New Cairo,...
1335              Jadie, 5th Settlement, New Cairo, Cairo
235     Mivida Compound, 5th Settlement, New Cairo, Cairo
Name: location, dtype: object

In [27]:
dupes = df.groupby(
    ["price", "location", "area", "beds","amenities"]
).size().reset_index(name="count")

dupes = dupes[dupes["count"] > 1]

dupes.sort_values("count", ascending=False).head(30)

,price,location,area,beds,amenities,count
1215,17750000,"Hyde Park New Cairo Compound, 5th Settlement, ...",160.0,3,"Covered parking, Electricity Meter, Water Mete...",5
109,3500000,"Obour City, Cairo",141.0,3,"Covered parking, Electricity Meter, Natural Ga...",4
640,7600000,"Al Maqsad, New Capital City, Cairo",135.0,3,"Covered parking, Electricity Meter, Water Mete...",4
1069,13850000,"Hyde Park New Cairo Compound, 5th Settlement, ...",116.0,2,"Covered parking, Electricity Meter, Water Mete...",4
563,7000000,"Jade Park, R3, New Capital City, Cairo",151.0,2,"Covered parking, Electricity Meter, Water Mete...",4
582,7100000,"Sarai, Mostakbal City, Cairo",150.0,3,"Built in Kitchen Appliances, Covered parking, ...",3
450,6000000,"Sarai, Mostakbal City, Cairo",131.0,3,"Built in Kitchen Appliances, Furnished, Covere...",2
478,6300000,"Bloomfields, Mostakbal City, Cairo",135.0,2,"Covered parking, Electricity Meter, Natural Ga...",2
487,6400000,"The Icon Residence Compound, 5th Settlement, N...",158.0,3,"Built in Kitchen Appliances, Covered parking, ...",2
491,6450000,"Taj City Compound, 1st Settlement, New Cairo, ...",132.0,3,"Built in Kitchen Appliances, Covered parking, ...",2
523,6600000,"Blue Vert, R7, New Capital City, Cairo",136.0,2,"Covered parking, Electricity Meter, Natural Ga...",2
233,4500000,"Sarai, Mostakbal City, Cairo",124.0,2,"Built in Kitchen Appliances, Covered parking, ...",2
572,7000000,"Stoda Residence, Sheraton, Cairo",154.0,3,"Covered parking, Electricity Meter, Natural Ga...",2
408,5800000,"The Icon Residence Compound, 5th Settlement, N...",125.0,2,"Covered parking, Pets Allowed, Electricity Met...",2
951,11500000,"Mountain View Hyde Park Compound, 5th Settlement",164.0,3,"Balcony, Private Garden, Covered Parking, Elec...",2
959,11600000,"EL Patio ORO Compound, 5th Settlement, New Cai...",164.0,3,"Covered parking, Pets Allowed, Water Meter, Na...",2
374,5500000,"The Icon Residence Compound, 5th Settlement, N...",162.0,3,"Built in Kitchen Appliances, Covered parking, ...",2
360,5500000,"Midtown Condo, New Capital City, Cairo",210.0,3,"Covered parking, Landline, Balcony or Terrace,...",2
1303,20197000,"Maadi View, Shorouk City, Cairo",376.0,3,"Covered parking, Electricity Meter, Balcony or...",2
1571,139970000,"City Gate Compound, 5th Settlement, New Cairo,...",565.0,4,"Balcony or Terrace, Covered parking, Reception...",2

In [29]:
sample_dup = dupes.iloc[5]

df[
    (df["price"] == sample_dup["price"]) &
    (df["location"] == sample_dup["location"]) &
    (df["area"] == sample_dup["area"]) &
    (df["beds"] == sample_dup["beds"]) & 
    (df["amenities"] == sample_dup["amenities"])
][
    [
        "title",
        "price",
        "location",
        "area",
        "beds",
        "amenities",
        "scraped_at",
        "link"
    ]
]

,title,price,location,area,beds,amenities,scraped_at,link
792,"With a 50% discount, own a 131-square-meter, 3...",6000000,"Sarai, Mostakbal City, Cairo",131.0,3,"Built in Kitchen Appliances, Furnished, Covere...",2026-05-11 12:23:52.873,https://www.bayut.eg/en/property/details-50334...
983,"With a 50% discount, own a 131-square-meter, 3...",6000000,"Sarai, Mostakbal City, Cairo",131.0,3,"Built in Kitchen Appliances, Furnished, Covere...",2026-05-11 12:27:14.878,https://www.bayut.eg/en/property/details-50346...

In [31]:
fuzzy_dupes = df.groupby(
    ["location", "area", "beds" , "amenities"]
).size().reset_index(name="count")

fuzzy_dupes = fuzzy_dupes[fuzzy_dupes["count"] > 1]

fuzzy_dupes.sort_values("count", ascending=False).head(20)

,location,area,beds,amenities,count
533,"Hyde Park New Cairo Compound, 5th Settlement, ...",160.0,3,"Covered parking, Electricity Meter, Water Mete...",5
522,"Hyde Park New Cairo Compound, 5th Settlement, ...",116.0,2,"Covered parking, Electricity Meter, Water Mete...",4
570,"Jade Park, R3, New Capital City, Cairo",151.0,2,"Covered parking, Electricity Meter, Water Mete...",4
106,"Al Maqsad, New Capital City, Cairo",135.0,3,"Covered parking, Electricity Meter, Water Mete...",4
1033,"Obour City, Cairo",141.0,3,"Covered parking, Electricity Meter, Natural Ga...",4
1232,"Sarai, Mostakbal City, Cairo",131.0,3,"Built in Kitchen Appliances, Furnished, Covere...",3
359,"EL Patio ORO Compound, 5th Settlement, New Cai...",164.0,3,"Covered parking, Pets Allowed, Water Meter, Na...",3
1236,"Sarai, Mostakbal City, Cairo",150.0,3,"Built in Kitchen Appliances, Covered parking, ...",3
33,"90 Avenue Compound, 5th Settlement, New Cairo,...",160.0,3,"Security Staff, CCTV Security",2
1487,"The Icon Residence Compound, 5th Settlement, N...",158.0,3,"Built in Kitchen Appliances, Covered parking, ...",2
1483,"The Icon Residence Compound, 5th Settlement, N...",125.0,2,"Covered parking, Pets Allowed, Electricity Met...",2
1417,"Taj City Compound, 1st Settlement, New Cairo, ...",132.0,3,"Built in Kitchen Appliances, Covered parking, ...",2
1394,"Taj City Compound, 1st Settlement",81.0,1,"Balcony, Private Garden, Security",2
1341,"Stoda Residence, Sheraton, Cairo",154.0,3,"Covered parking, Electricity Meter, Natural Ga...",2
1333,"Stei8ht Compound, 1st Settlement, New Cairo, C...",390.0,4,"Covered parking, Pets Allowed, Electricity Met...",2
987,"New Narges, 5th Settlement, New Cairo, Cairo",165.0,3,"Covered parking, Pets Allowed, Electricity Met...",2
1228,"Sarai, Mostakbal City, Cairo",124.0,2,"Built in Kitchen Appliances, Covered parking, ...",2
989,"New Narges, 5th Settlement, New Cairo, Cairo",166.0,3,"Electricity Meter, Water Meter",2
873,"Mountain View Hyde Park Compound, 5th Settlement",164.0,3,"Balcony, Private Garden, Covered Parking, Elec...",2
823,"Midtown Condo, New Capital City, Cairo",210.0,3,"Covered parking, Landline, Balcony or Terrace,...",2

In [35]:
sample = fuzzy_dupes.iloc[1]

df[
    (df["location"] == sample["location"]) &
    (df["area"] == sample["area"]) &
    (df["beds"] == sample["beds"]) 
][
    [
        "title",
        "price",
        "location",
        "area",
        "beds",
        "scraped_at",
        "link"
    ]
]

,title,price,location,area,beds,scraped_at,link
479,Fully Finished Apartment view on iconic tower ...,3282000,"Al Maqsad, New Capital City, Cairo",135.0,3,2026-05-11 12:22:32.095,https://www.bayut.eg/en/property/details-50348...
1093,Ready to move with installments over 10 years ...,7600000,"Al Maqsad, New Capital City, Cairo",135.0,3,2026-05-11 12:29:24.514,https://www.bayut.eg/en/property/details-50294...
1249,"Prime location apartment, fully finished and r...",7600000,"Al Maqsad, New Capital City, Cairo",135.0,3,2026-05-11 12:31:56.816,https://www.bayut.eg/en/property/details-50295...
1250,With only a 5% down payment and installments o...,7600000,"Al Maqsad, New Capital City, Cairo",135.0,3,2026-05-11 12:31:57.051,https://www.bayut.eg/en/property/details-50295...
1251,"With a down payment of 380,000 and installment...",7600000,"Al Maqsad, New Capital City, Cairo",135.0,3,2026-05-11 12:31:57.520,https://www.bayut.eg/en/property/details-50295...

In [37]:
sample = fuzzy_dupes.iloc[0]

test = df[
    (df["location"] == sample["location"]) &
    (df["area"] == sample["area"]) &
    (df["beds"] == sample["beds"]) & 
    (df['amenities'] == sample['amenities'])
]

test[["price", "title", "link", "scraped_at"]]

,price,title,link,scraped_at
1174,13000000,Ground Apartment with Private Garden for Sale,https://www.bayut.eg/en/property/details-50321...,2026-05-11 12:31:30.717
1662,14000000,Ground Apartment with Pool View for Sale in 90...,https://www.bayut.eg/en/property/details-50321...,2026-05-11 12:35:15.287

In [42]:
df["listing_id"] = df["link"].str.extract(r'(\d+)')

In [46]:
df["listing_id"].duplicated().sum()

np.int64(104)

In [47]:
dupe_ids = df[df["listing_id"].duplicated(keep=False)]

dupe_ids.sort_values("listing_id")[
    [
        "listing_id",
        "price",
        "title",
        "scraped_at",
        "link"
    ]
].head(20)

,listing_id,price,title,scraped_at,link
523,1,17000000,NaN,2026-05-11 18:33:07.081,https://www.dubizzle.com.eg/en/ad/moon-valley-...
955,1,8000000,NaN,2026-05-12 19:32:29.965,https://www.dubizzle.com.eg/en/ad/al-rihab-1-t...
878,1,5150000,NaN,2026-05-11 18:57:33.614,https://www.dubizzle.com.eg/en/ad/garden-view-...
662,1,11750000,NaN,2026-05-11 18:57:26.240,https://www.dubizzle.com.eg/en/ad/luxury-apart...
458,10,18500000,NaN,2026-05-11 18:33:05.005,https://www.dubizzle.com.eg/en/ad/lowest-down-...
526,10,13338727,NaN,2026-05-11 18:33:07.875,https://www.dubizzle.com.eg/en/ad/apartment-fo...
15,10,8500000,NaN,2026-05-10 18:26:55.731,https://www.dubizzle.com.eg/en/ad/best-price-i...
857,10,11000000,NaN,2026-05-11 18:57:32.640,https://www.dubizzle.com.eg/en/ad/my-city-b10-...
48,11,4100000,NaN,2026-05-10 18:27:03.224,https://www.dubizzle.com.eg/en/ad/for-sale-in-...
1679,11,6200000,NaN,2026-05-10 18:27:05.500,https://www.dubizzle.com.eg/en/ad/apartment-fo...
41,12,5300000,NaN,2026-05-11 18:32:50.871,https://www.dubizzle.com.eg/en/ad/apartment-fo...
1004,12,6650000,NaN,2026-05-12 19:32:35.316,https://www.dubizzle.com.eg/en/ad/apartment-fo...
18,135,10000000,NaN,2026-05-11 18:32:49.546,https://www.dubizzle.com.eg/en/ad/luxury-135-s...
966,135,6700000,NaN,2026-05-12 19:32:31.958,https://www.dubizzle.com.eg/en/ad/apartment-fo...
782,136,9100000,NaN,2026-05-11 18:57:30.026,https://www.dubizzle.com.eg/en/ad/136-sqm-grou...
265,136,3981955,NaN,2026-05-11 18:32:58.832,https://www.dubizzle.com.eg/en/ad/apartment-fo...
165,136,9100000,NaN,2026-05-11 18:32:54.768,https://www.dubizzle.com.eg/en/ad/apartment-13...
112,145,3400000,NaN,2026-05-11 18:32:53.134,https://www.dubizzle.com.eg/en/ad/apartment-fo...
1075,145,3000000,NaN,2026-05-12 19:32:45.914,https://www.dubizzle.com.eg/en/ad/apartment-ea...
397,145,2900000,NaN,2026-05-11 18:33:02.737,https://www.dubizzle.com.eg/en/ad/145-sqm-rear...

In [35]:
sample_id = dupe_ids["listing_id"].iloc[0]

df[df["listing_id"] == sample_id][
    [
        "price",
        "title",
        "amenities",
        "scraped_at",
        "link"
    ]
]

,price,title,amenities,scraped_at,link
1,12500000,None,"Air Conditioning, Covered Parking",2026-05-09 11:07:41.680,https://www.dubizzle.com.eg/en/ad/for-sale-a-h...
4,12500000,None,"Air Conditioning, Covered Parking",2026-05-09 13:55:43.702,https://www.dubizzle.com.eg/en/ad/for-sale-hea...

In [48]:
df = df.sort_values("scraped_at")

In [51]:
df_latest = df.drop_duplicates(
    subset="listing_id",
    keep="last"
)

In [38]:
print(len(df))
print(len(df_latest))

1976
1898

In [52]:
df_analysis = df_latest.copy()

In [55]:
df_analysis["is_studio"] = (
    df_analysis["beds"] == "Studio"
)

df_analysis["beds_clean"] = pd.to_numeric(
    df_analysis["beds"],
    errors="coerce"
).astype("Int64")

In [58]:
df_analysis[
    ["beds", "beds_clean", "is_studio"]
].sample(250)

        beds  beds_clean  is_studio
1381       4           4      False
173   Studio        <NA>       True
1877       4           4      False
515        6           6      False
1127       3           3      False
...      ...         ...        ...
171        3           3      False
1689       2           2      False
1228       3           3      False
1567       3           3      False
895        3           3      False

[250 rows x 3 columns]

In [59]:
df_analysis["beds_clean"].dtype

Int64Dtype()

In [43]:
df_analysis["price"].head()

1581       45000
3         250000
4       12500000
6          25000
7          55000
Name: price, dtype: int64

In [44]:
df_analysis["price"].dtype

dtype('int64')

In [60]:
df_analysis["price_clean"] = pd.to_numeric(
    df_analysis["price"],
    errors="coerce"
)

In [46]:
df_analysis["price_clean"].describe()

count    1.898000e+03
mean     1.439512e+07
std      1.868315e+07
min      2.500000e+04
25%      5.591120e+06
50%      9.000000e+06
75%      1.625509e+07
max      3.120000e+08
Name: price_clean, dtype: float64

In [63]:
df_analysis["price_per_sqm"] = (
    df_analysis["price_clean"] /
    df_analysis["area"]
)

In [48]:
df_analysis["price_per_sqm"].describe()

count      1898.000000
mean      60728.852161
std       35753.377348
min         142.857143
25%       36290.322581
50%       54000.000000
75%       75519.606135
max      423529.411765
Name: price_per_sqm, dtype: float64

In [64]:
df_analysis.sort_values(
    "price_per_sqm"
)[
    [
        "price_clean",
        "area",
        "price_per_sqm",
        "property_type",
        "location",
        "link"
    ]
].head(20)

,price_clean,area,price_per_sqm,property_type,location,link
6,25000,175.0,142.857143,Office Space,"Laurent, Alexandria",https://www.dubizzle.com.eg/en/ad/office-for-r...
1670,30000,210.0,142.857143,Office Space,"Darna, Zahraa Al Maadi",https://www.dubizzle.com.eg/en/ad/office-headq...
7,55000,270.0,203.703704,Office Space,"Smoha, Alexandria",https://www.dubizzle.com.eg/en/ad/distinct-adm...
1667,45000,200.0,225.000000,Office Space,"Bavaria Town, Zahraa Al Maadi",https://www.dubizzle.com.eg/en/ad/administrati...
1669,60000,200.0,300.000000,Office Space,"Rayhanah Plaza, Zahraa Al Maadi",https://www.dubizzle.com.eg/en/ad/for-rent-an-...
3,250000,260.0,961.538462,Office Space,"One Katameya, Katameya",https://www.dubizzle.com.eg/en/ad/for-rent-an-...
1953,1500000,420.0,3571.428571,Duplex,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50345...
2046,800000,209.0,3827.751196,Land,"New Obour City, Obour City, Cairo",https://www.bayut.eg/en/property/details-50344...
1991,1800000,300.0,6000.000000,Duplex,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50330...
1125,1700000,280.0,6071.428571,Duplex,"El Motamayez District, Badr City, Cairo",https://www.bayut.eg/en/property/details-50344...
1121,3000000,400.0,7500.000000,Duplex,"El Motamayez District, Badr City, Cairo",https://www.bayut.eg/en/property/details-50344...
1113,1300000,140.0,9285.714286,Apartment,"El Motamayez District, Badr City, Cairo",https://www.bayut.eg/en/property/details-50344...
831,1400000,140.0,10000.000000,Apartment,"El Motamayez District, Badr City, Cairo",https://www.bayut.eg/en/property/details-50348...
1615,1500000,145.0,10344.827586,Apartment,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50096...
1283,1550000,145.0,10689.655172,Apartment,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50349...
113,8000000,700.0,11428.571429,Villa,"Mivida Compound, 5th Settlement, New Cairo, Cairo",https://www.bayut.eg/en/property/details-20501...
1797,5200000,450.0,11555.555556,Duplex,"Shorouk City, Cairo",https://www.bayut.eg/en/property/details-50348...
1614,1450000,120.0,12083.333333,Apartment,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50327...
508,1400000,115.0,12173.913043,Apartment,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50301...
1265,1350000,110.0,12272.727273,Apartment,"Badr City, Cairo",https://www.bayut.eg/en/property/details-50318...

In [ ]:
import numpy as np


df_analysis["transaction_type"] = np.where(
    df_analysis["link"].str.contains("for-rent"),
    "for_rent",
    "for_sale"
)

,id,checksum,price,location,title,beds,baths,area,property_type,furnishing,...,reactivated_date,source,scraped_at,transformed_at,listing_id,is_studio,beds_clean,price_clean,price_per_sqm,transaction_type
1667,3,0cefb06cedd39bd9e6652e861d0dd319,45000,"Bavaria Town, Zahraa Al Maadi",NaN,NaN,NaN,200.0,Office Space,Unfurnished,...,2026-05-09 11:08:17.964,dubizzle,2026-05-09 11:08:17.964,2026-05-10 18:27:16.485007,503056078,False,<NA>,45000,225.000000,for_rent
3,4,02ac686ec68f0d48ff0f7ad6a7410057,250000,"One Katameya, Katameya",NaN,NaN,NaN,260.0,Office Space,Furnished,...,2026-05-09 11:08:18.180,dubizzle,2026-05-09 11:08:18.180,2026-05-10 18:27:16.827983,502700763,False,<NA>,250000,961.538462,for_rent
6,7,e3f5778ef80fa173e03aff432ddc728d,25000,"Laurent, Alexandria",NaN,NaN,NaN,175.0,Office Space,Unfurnished,...,2026-05-09 13:56:48.026,dubizzle,2026-05-09 13:56:48.026,2026-05-10 18:27:17.856575,503449628,False,<NA>,25000,142.857143,for_rent
7,8,981efbfb1974479d7a0906c2a7043a22,55000,"Smoha, Alexandria",NaN,NaN,NaN,270.0,Office Space,Unfurnished,...,2026-05-09 13:56:53.909,dubizzle,2026-05-09 13:56:53.909,2026-05-10 18:27:18.205719,270,False,<NA>,55000,203.703704,for_rent
1669,9,f3598efdbe376e8d8d6f3607224c6838,60000,"Rayhanah Plaza, Zahraa Al Maadi",NaN,NaN,NaN,200.0,Office Space,Unfurnished,...,2026-05-09 13:57:11.115,dubizzle,2026-05-09 13:57:11.115,2026-05-10 18:27:18.544924,503485836,False,<NA>,60000,300.000000,for_rent
1670,10,044cab5dfabeb090b850382c3bb2758b,30000,"Darna, Zahraa Al Maadi",NaN,NaN,NaN,210.0,Office Space,Unfurnished,...,2026-05-09 13:57:11.581,dubizzle,2026-05-09 13:57:11.581,2026-05-10 18:27:18.927035,503485830,False,<NA>,30000,142.857143,for_rent

In [66]:
df_analysis["transaction_type"].value_counts()

transaction_type
for_sale    1952
for_rent       6
Name: count, dtype: int64

In [73]:
df_analysis.groupby(
    "transaction_type"
)["price_per_sqm"].describe()

,count,mean,std,min,25%,50%,75%,max
transaction_type,,,,,,,,
for_rent,6.0,329.326075,315.201128,142.857143,158.068783,214.351852,281.250000,961.538462
for_sale,1952.0,60795.687911,35472.807140,3571.428571,36363.636364,54141.003421,75609.756098,423529.411765

In [74]:
df_analysis["amenities"].dropna().sample(10)

1103    Covered parking, Pets Allowed, Electricity Met...
356                                    Balcony or Terrace
1212    Built in Kitchen Appliances, Electricity Meter...
678     Electricity Meter, Water Meter, Natural Gas, L...
1610    Electricity Meter, Water Meter, Natural Gas, B...
654     Built in Kitchen Appliances, Electricity Meter...
1011    Balcony or Terrace, Kids Play Area, Security S...
547     First Aid Medical Center, Gym or Health Club, ...
724     Balcony or Terrace, Swimming Pool, Covered par...
251     Covered parking, Electricity Meter, Balcony or...
Name: amenities, dtype: str

In [76]:
all_amenities = (
    df_analysis["amenities"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

all_amenities.value_counts().head(50)

amenities
Electricity Meter              1032
Water Meter                     930
Security Staff                  930
Natural Gas                     920
Lawn or Garden                  914
Covered parking                 900
Pets Allowed                    866
Balcony or Terrace              825
Landline                        797
Gym or Health Club              776
Kids Play Area                  774
Barbeque Area                   709
CCTV Security                   659
Maintenance Staff               650
Swimming Pool                   643
Cafeteria or Canteen            604
Day Care Center                 575
First Aid Medical Center        564
Cleaning Services               554
Jacuzzi                         511
Built in Kitchen Appliances     499
Waste Disposal                  489
Sauna                           450
Facilities for Disabled         427
24 Hours Concierge              425
Broadband Internet              403
Steam Room                      395
Satellite/Cable TV              358
Business Center                 354
Lobby in Building               351
Intercom                        347
Laundry Room                    345
Freehold                        299
Laundry Facility                294
Conference Room                 287
Maids Room                      253
Shared Kitchen                  253
Double Glazed Windows           239
Service Elevators               232
Storage Areas                   226
Reception/Waiting Room          226
Central A/C & heating           225
Electricity Backup              218
Centrally Air-Conditioned       202
Prayer Room                     180
ATM Facility                    170
Central Heating                 169
Study Room                      143
Sea view                        136
Furnished                       119
Name: count, dtype: int64

In [77]:
amenity_map = {

    "Central A/C & heating": "Central AC",

    "Centrally Air-Conditioned": "Central AC",

    "Laundry Facility": "Laundry",

    "Laundry Room": "Laundry",

    "Balcony or Terrace": "Balcony",

    "Covered parking": "Covered Parking"

}

In [78]:
amenity_map = {

    "Central A/C & heating": "Central AC",

    "Centrally Air-Conditioned": "Central AC",

    "Laundry Facility": "Laundry",

    "Laundry Room": "Laundry",

    "Balcony or Terrace": "Balcony",

    "Covered parking": "Covered Parking"

}

def normalize_amenities(text):

    if pd.isna(text):
        return None

    items = [
        x.strip()
        for x in text.split(",")
    ]

    normalized = [
        amenity_map.get(item, item)
        for item in items
    ]

    return ", ".join(
        sorted(set(normalized))
    )

In [79]:
df_analysis["amenities_clean"] = (
    df_analysis["amenities"]
    .apply(normalize_amenities)
)

df_analysis['amenities_clean'].head(20)

1667                                                  NaN
3                                        Air Conditioning
4                       Air Conditioning, Covered Parking
6                               Covered Parking, Security
7                                                Security
1669                                                  NaN
1670                                                  NaN
1671                                                  NaN
1672                                                  NaN
24                      Balcony, Private Garden, Security
26      Balcony, Built in Kitchen Appliances, Central ...
27      Balcony, Built in Kitchen Appliances, Covered ...
28      Balcony, Built in Kitchen Appliances, Pets All...
29                  Balcony, Pets Allowed, Private Garden
35                               Private Garden, Security
38      Built in Kitchen Appliances, Covered Parking, ...
39                         Pool, Private Garden, Security
40                         Pool, Private Garden, Security
42      Covered Parking, Electricity Meter, Landline, ...
1677                                                  NaN
Name: amenities_clean, dtype: str

In [80]:
df_analysis[
    ["amenities", "amenities_clean"]
].sample(10)

,amenities,amenities_clean
1732,NaN,NaN
1282,"Covered parking, Balcony or Terrace, Gym or He...","Balcony, Barbeque Area, Cafeteria or Canteen, ..."
1799,NaN,NaN
303,"Covered parking, Pets Allowed, Water Meter, Na...","Covered Parking, Landline, Natural Gas, Pets A..."
283,"Pets Allowed, Balcony or Terrace, Completion Y...","Balcony, Completion Year, First Aid Medical Ce..."
1228,"Built in Kitchen Appliances, Covered parking, ...","Barbeque Area, Built in Kitchen Appliances, Ca..."
920,"Balcony or Terrace, View, Completion Year, Law...","Balcony, Completion Year, Lawn or Garden, View"
1507,"Built in Kitchen Appliances, Covered parking, ...","Barbeque Area, Built in Kitchen Appliances, Ca..."
1896,NaN,NaN
1115,"Built in Kitchen Appliances, Covered parking, ...","Balcony, Barbeque Area, Built in Kitchen Appli..."

In [81]:
df['amenities']

1666                                                  NaN
1                       Air Conditioning, Covered Parking
1667                                                  NaN
3                                        Air Conditioning
4                       Air Conditioning, Covered Parking
                              ...
1382    Built in Kitchen Appliances, Covered parking, ...
1393    Built in Kitchen Appliances, Covered parking, ...
1394    Covered parking, Pets Allowed, Electricity Met...
1395    Built in Kitchen Appliances, Covered parking, ...
1397    Covered parking, Pets Allowed, Electricity Met...
Name: amenities, Length: 2062, dtype: str

In [82]:
df

,id,checksum,price,location,title,beds,baths,area,property_type,furnishing,amenities,link,reactivated_date,source,scraped_at,transformed_at,listing_id
1666,1,3d9254329d461122a077bf186d1dd17f,60000,"Rayhanah Plaza, Zahraa Al Maadi",NaN,NaN,NaN,200.0,Office Space,Unfurnished,NaN,https://www.dubizzle.com.eg/en/ad/for-rent-an-...,2026-05-09 09:34:37.532,dubizzle,2026-05-09 09:34:37.532,2026-05-10 18:27:15.555913,503485836
1,2,e1a8744d5c417095655c2fadc395a4e0,12500000,"Shubra, Cairo",NaN,NaN,NaN,200.0,Office Space,Unfurnished,"Air Conditioning, Covered Parking",https://www.dubizzle.com.eg/en/ad/for-sale-a-h...,2026-05-09 11:07:41.679,dubizzle,2026-05-09 11:07:41.680,2026-05-10 18:27:16.054129,503362090
1667,3,0cefb06cedd39bd9e6652e861d0dd319,45000,"Bavaria Town, Zahraa Al Maadi",NaN,NaN,NaN,200.0,Office Space,Unfurnished,NaN,https://www.dubizzle.com.eg/en/ad/administrati...,2026-05-09 11:08:17.964,dubizzle,2026-05-09 11:08:17.964,2026-05-10 18:27:16.485007,503056078
3,4,02ac686ec68f0d48ff0f7ad6a7410057,250000,"One Katameya, Katameya",NaN,NaN,NaN,260.0,Office Space,Furnished,Air Conditioning,https://www.dubizzle.com.eg/en/ad/for-rent-an-...,2026-05-09 11:08:18.180,dubizzle,2026-05-09 11:08:18.180,2026-05-10 18:27:16.827983,502700763
4,5,9cbddb0a16e1d839fc4451eca2617920,12500000,"Shubra, Cairo",NaN,NaN,NaN,200.0,Office Space,Unfurnished,"Air Conditioning, Covered Parking",https://www.dubizzle.com.eg/en/ad/for-sale-hea...,2026-05-09 13:55:43.702,dubizzle,2026-05-09 13:55:43.702,2026-05-10 18:27:17.172836,503362090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382,2058,3e73c5b67746a9d619a16a89fe63ace7,15000000,"Swan Lake Residences, 1st Settlement, New Cair...",Distinctive Apartment for Sale at a Special Pr...,3,4.0,176.0,Apartment,Unfurnished,"Built in Kitchen Appliances, Covered parking, ...",https://www.bayut.eg/en/property/details-50349...,2026-05-11 00:00:00.000,bayut,2026-05-12 20:44:13.630,2026-05-12 20:44:33.737725,503497033
1393,2059,4d798faaa451854b66ee975e1fdd0024,55000000,"East vale sodic, Mostakbal City, Cairo",Grand villa 4 bedrooms fully finished with Acc...,4,4.0,561.0,Villa,NaN,"Built in Kitchen Appliances, Covered parking, ...",https://www.bayut.eg/en/property/details-50350...,2026-05-12 00:00:00.000,bayut,2026-05-12 20:44:14.142,2026-05-12 20:44:34.144307,503501168
1394,2060,7d255128f87af3fbafed6cc9e77ea775,13837500,"Eastown Compound, 5th Settlement, New Cairo, C...",Apartment for sale in Sodic Eastown – Eastown ...,2,3.0,150.0,Apartment,Unfurnished,"Covered parking, Pets Allowed, Electricity Met...",https://www.bayut.eg/en/property/details-50343...,2026-05-11 00:00:00.000,bayut,2026-05-12 20:44:14.630,2026-05-12 20:44:34.585723,503437619
1395,2061,9565df5c2b14339abda1a45543779782,20000000,"Hyde Park New Cairo Compound, 5th Settlement, ...",Very hot price prime location ready to move to...,4,4.0,200.0,Townhouse,Unfurnished,"Built in Kitchen Appliances, Covered parking, ...",https://www.bayut.eg/en/property/details-50323...,2026-05-10 00:00:00.000,bayut,2026-05-12 20:44:15.134,2026-05-12 20:44:35.110909,503239135
1397,2062,57ccfa644d6732580ba50a1763a68b03,1350000,"Badr City, Cairo",Apartment available for immediate delivery on ...,3,2.0,110.0,Apartment,Unfurnished,"Covered parking, Pets Allowed, Electricity Met...",https://www.bayut.eg/en/property/details-50316...,2026-05-10 00:00:00.000,bayut,2026-05-12 20:44:15.528,2026-05-12 20:44:35.502383,503162677